---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: helloworld-postgres
type: Opaque
stringData:
  DB_PASSWORD: "REPLACE_WITH_YOUR_PASSWORD"
  DB_URL: "REPLACE_WITH_YOUR_CONNECTION_URL"
  DB_CERT: "REPLACE_WITH_YOUR_BASE64_CERT"